on_boot: 
    - switch.turn_on:
        id: mute_switch_real
    - text_sensor.template.publish:
        id: va_status
        state: "Booting"
    - light.control:
        id: va_listener
        red: 0%
        green: 100%
        blue: 50%
        brightness: 50%
    - light.turn_on:
        id: va_feedback
        brightness: 30%
        effect: aurora
    - delay: 5s
    - light.control:
        id: va_feedback
        brightness: 50%
    - delay: 5s
    - light.control:
        id: va_feedback
        brightness: 80%
    - delay: 5s
    - light.control:
        id: va_feedback
        brightness: 100%
    - delay: 15s
    - light.turn_off:
        id: va_feedback