esphome:
  min_version: "2024.5.0"
  name: ${name}
  friendly_name: ${friendly_name}
  name_add_mac_suffix: ${name_add_mac_suffix}
  platformio_options:
    board_build.flash_mode: dio
  project:
    name: ${project_name}
    version: ${project_version}
  <<: !include ../includes/esphome/on_boot.yaml

# Enable Home Assistant API
api:

# Allow Over-The-Air updates
ota:
  platform: esphome

# update:
#   - platform: http_request
#     name: Firmware Update
#     source: https://raw.githubusercontent.com/AuroraSmartHome/aurora-voice/main/manifest.json
